FROM $baseImage
LABEL maintainer="$maintainer"

# INSTALL COMPI
ADD image-files/compi.tar.gz /

# PLACE HERE YOUR DEPENDENCIES (SOFTWARE NEEDED BY YOUR PIPELINE)




# ADD PIPELINE
ADD pipeline.xml pipeline.xml
ENTRYPOINT ["/compi", "run",  "-p", "/pipeline.xml"]
