#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
$DIR/compi-files/jre/bin/java -Denvsubst.path=$DIR/compi-files/envsubst -jar "$DIR/compi-files/${project.artifactId}-${project.version}-jar-with-dependencies.jar" "$@"
